DEFINES+=PROJECT_CONF_H=\"project-conf.h\"
CONTIKI_PROJECT = pwm_test

TARGETDIRS += ../../platform

all: $(CONTIKI_PROJECT)

# CONTIKI_WITH_IPV6 = 0

CONTIKI = ../../../../contiki
include $(CONTIKI)/Makefile.include
